### ISSUE TITLE
gram_loss.append(mx.sym.sum(mx.sym.square(gvar - gram[i])))

### ISSUE THREAD

**Issue by yuzhuqingyun** [pavelgonchar/neural-art-mini#1]
hi!when i running ,there is an error:
    **gram_loss.append(mx.sym.sum(mx.sym.square(gvar - gram[i])))
AttributeError: 'module' object has no attribute 'sum'**
my mxnet tag is 20160321 and neural-style is ok.

**Comment by pavelgonchar** [comment]
Hi,

`
cd /path/to/mxnet
`
`
git pull && git submodule update && make clean && make
`
`
cd python
`
`
python setup.py install
`
